In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('result/ori-replaced-edited.csv')
df

,Unnamed: 0,Class,Replaced Element,Replaced Level,Same Result/ Can Replaced,Unnamed: 5
0,7024,map' call function,Simple List,1.0,True,NaN
1,7024,map' call function,Simple Atributte,2.0,True,NaN
2,7024,map' call function,Simple Assignment,1.0,True,NaN
3,7024,map' call function,Simple For Loop,1.0,True,NaN
4,7261,Import're' module,Generator Expression,5.0,False,NaN
...,...,...,...,...,...,...
200,414,Simple Dictionary Comprehension,Simple Assignment,1.0,True,NaN
201,414,Simple Dictionary Comprehension,Simple For Loop,1.0,True,NaN
202,4514,Generator Function (yield),pass' statement,3.0,False,NaN
203,823,Super Function,Simple Atributte,2.0,True,less flexible and can lead issue
204,824,Super Function,Simple Atributte,2.0,True,less flexible and can lead issue

In [3]:
ele = df['Unnamed: 0'].unique()
ele

array([7024, 7261, 8337, 8198, 8199, 5710, 6295, 5465, 5466, 5467, 5264,
       5123, 5124, 5125, 7960, 6259, 6606, 6996, 6997, 6607, 6250, 6251,
       6021, 6022, 6024, 6023, 7171, 7172, 8041, 8042, 8015, 7513, 7514,
       7955, 7956, 7957, 7958, 7959, 7679, 7681, 7515,  724, 4714, 2931,
       2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 4048, 4049, 2928,
       2929,  414, 4514,  823,  824])

In [4]:
len(ele)

60

In [5]:
df_map = df[['Unnamed: 0', 'Class']].drop_duplicates()
df_map

     Unnamed: 0                                   Class
0          7024                      map' call function
4          7261                       Import're' module
9          8337         Simple Dictionary Comprehension
14         8198                          Super Function
15         8199                          Super Function
16         5710                       Import're' module
17         6295                Import'importlib' module
26         5465              Generator Function (yield)
31         5466              Generator Function (yield)
36         5467              Generator Function (yield)
42         5264               Simple List Comprehension
46         5123                          Super Function
48         5124                          Super Function
50         5125                          Super Function
52         7960                          Super Function
53         6259         Simple Dictionary Comprehension
58         6606                    Generator Expression
63         6996              Generator Function (yield)
65         6997              Generator Function (yield)
67         6607         Simple Dictionary Comprehension
72         6250              Generator Function (yield)
73         6251              Generator Function (yield)
74         6021  List Comprehension with 1If statements
80         6022  List Comprehension with 1If statements
85         6024         Simple Dictionary Comprehension
89         6023               Simple List Comprehension
93         7171                    Generator Expression
97         7172                    Generator Expression
101        8041                    Generator Expression
107        8042                    Generator Expression
113        8015                          Super Function
114        7513                    Generator Expression
118        7514                    Generator Expression
123        7955              Generator Function (yield)
124        7956              Generator Function (yield)
125        7957              Generator Function (yield)
126        7958              Generator Function (yield)
127        7959              Generator Function (yield)
128        7679                       Import're' module
129        7681                   Import'struct' module
130        7515         Simple Dictionary Comprehension
134         724              Generator Function (yield)
139        4714               Simple List Comprehension
145        2931                    Generator Expression
149        2932                    Generator Expression
153        2933                    Generator Expression
158        2934                    Generator Expression
163        2935                    Generator Expression
168        2936                    Generator Expression
173        2937                    Generator Expression
178        2938                    Generator Expression
183        2939                    Generator Expression
188        4048                   Import'pickle' module
189        4049                       Import're' module
190        2928               Simple List Comprehension
194        2929               Simple List Comprehension
198         414         Simple Dictionary Comprehension
202        4514              Generator Function (yield)
203         823                          Super Function
204         824                          Super Function

In [6]:
start_df = []

for i, row in df_map.iterrows():
    ele_num = row['Unnamed: 0']
    cls = row['Class']
    df_search = df[df['Unnamed: 0']== ele_num]
#     print(df_search)
    df_score = df_search['Replaced Level'].to_list()
    df_score = sorted(df_score)
    unique_element = df_search['Replaced Element'].unique()
    unique_element_sort = sorted(unique_element)
#     print(ele_num)
#     print(unique_element_sort)
    start_df.append([ele_num, cls, unique_element_sort, df_score])
#     print('-------------------------------------------')

In [7]:
# Convert the list of lists to a DataFrame
start_df_df = pd.DataFrame(start_df, columns=['i', 'Class', 'unique_element_sort', 'score_list'])

# Save the DataFrame to a CSV file
# start_df_df.to_csv('result/element/all.csv', index=False)
start_df_df.to_csv('result/element/all-withscore.csv', index=False)

## Find unique

In [8]:
new_df = start_df_df
new_df

,i,Class,unique_element_sort,score_list
0,7024,map' call function,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
1,7261,Import're' module,"[Function with Simple argument, Generator Expr...","[1.0, 1.0, 1.0, 1.0, 5.0]"
2,8337,Simple Dictionary Comprehension,"[Return, Simple Assignment, Simple Atributte, ...","[1.0, 1.0, 1.0, 2.0, 2.0]"
3,8198,Super Function,[Simple Atributte],[2.0]
4,8199,Super Function,[Simple Atributte],[2.0]
5,5710,Import're' module,[nan],[nan]
6,6295,Import'importlib' module,"[Exception --> try/except, For Loop with 1 Tup...","[1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0]"
7,5465,Generator Function (yield),"[Return, Simple Assignment, Simple Atributte, ...","[1.0, 1.0, 1.0, 1.0, 2.0]"
8,5466,Generator Function (yield),"[Return, Simple Assignment, Simple Atributte, ...","[1.0, 1.0, 1.0, 1.0, 2.0]"
9,5467,Generator Function (yield),"[Return, Simple Assignment, Simple Atributte, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 2.0]"
10,5264,Simple List Comprehension,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
11,5123,Super Function,"[Return, Simple Atributte]","[1.0, 2.0]"
12,5124,Super Function,"[Return, Simple Atributte]","[1.0, 2.0]"
13,5125,Super Function,"[Return, Simple Atributte]","[1.0, 2.0]"
14,7960,Super Function,[Simple Atributte],[2.0]
15,6259,Simple Dictionary Comprehension,"[Return, Simple Assignment, Simple Dictionary,...","[1.0, 1.0, 1.0, 1.0, 2.0]"
16,6606,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 1.0, 2.0]"
17,6996,Generator Function (yield),"[Generator Function (yield), Simple For Loop]","[1.0, 5.0]"
18,6997,Generator Function (yield),"[Generator Function (yield), Simple For Loop]","[1.0, 5.0]"
19,6607,Simple Dictionary Comprehension,"[Return, Simple Assignment, Simple Atributte, ...","[1.0, 1.0, 1.0, 2.0, 2.0]"
20,6250,Generator Function (yield),[Return],[1.0]
21,6251,Generator Function (yield),[Return],[1.0]
22,6021,List Comprehension with 1If statements,"[For Loop with Tuple as name, Simple Assignmen...","[1.0, 1.0, 1.0, 1.0, 2.0, 2.0]"
23,6022,List Comprehension with 1If statements,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 1.0, 2.0]"
24,6024,Simple Dictionary Comprehension,"[Simple Assignment, Simple Atributte, Simple D...","[1.0, 1.0, 2.0, 2.0]"
25,6023,Simple List Comprehension,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
26,7171,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
27,7172,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
28,8041,Generator Expression,"[For Loop with Tuple as name, Return, Simple A...","[1.0, 1.0, 1.0, 1.0, 2.0, 2.0]"
29,8042,Generator Expression,"[For Loop with Tuple as name, Return, Simple A...","[1.0, 1.0, 1.0, 1.0, 2.0, 2.0]"
30,8015,Super Function,[Simple Atributte],[2.0]
31,7513,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
32,7514,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 1.0, 2.0]"
33,7955,Generator Function (yield),[Return],[1.0]
34,7956,Generator Function (yield),[Return],[1.0]
35,7957,Generator Function (yield),[Return],[1.0]
36,7958,Generator Function (yield),[Return],[1.0]
37,7959,Generator Function (yield),[Return],[1.0]
38,7679,Import're' module,[nan],[nan]
39,7681,Import'struct' module,[nan],[nan]
40,7515,Simple Dictionary Comprehension,"[Simple Assignment, Simple Atributte, Simple D...","[1.0, 1.0, 2.0, 2.0]"
41,724,Generator Function (yield),"[For Loop with 1 List to iterate, Generator Fu...","[1.0, 1.0, 2.0, 2.0, 5.0]"
42,4714,Simple List Comprehension,"[For Loop with Tuple as name, Simple Assignmen...","[1.0, 1.0, 1.0, 2.0, 2.0, 2.0]"
43,2931,Generator Expression,"[For Loop with 1 List to iterate, Simple Assig...","[1.0, 1.0, 2.0, 2.0]"
44,2932,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
45,2933,Generator Expression,"[Simple Assignment, Simple For Loop, Simple If...","[1.0, 1.0, 1.0, 3.0, 4.0]"
46,2934,Generator Expression,"[Simple Assignment, Simple For Loop, Simple If...","[1.0, 1.0, 1.0, 3.0, 4.0]"
47,2935,Generator Expression,"[Simple Assignment, Simple For Loop, Simple If...","[1.0, 1.0, 1.0, 3.0, 4.0]"
48,2936,Generator Expression,"[For Loop with Tuple as name, Simple Assignmen...","[1.0, 1.0, 1.0, 2.0, 2.0]"
49,2937,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0, 2.0]"
50,2938,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0, 4.0]"
51,2939,Generator Expression,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0, 4.0]"
52,4048,Import'pickle' module,[nan],[nan]
53,4049,Import're' module,[nan],[nan]
54,2928,Simple List Comprehension,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
55,2929,Simple List Comprehension,"[Simple Assignment, Simple Atributte, Simple F...","[1.0, 1.0, 1.0, 2.0]"
56,414,Simple Dictionary Comprehension,"[Simple Assignment, Simple Atributte, Simple D...","[1.0, 1.0, 2.0, 2.0]"
57,4514,Generator Function (yield),[pass' statement],[3.0]
58,823,Super Function,[Simple Atributte],[2.0]
59,824,Super Function,[Simple Atributte],[2.0]

In [9]:
# Assuming new_df is already defined and contains the relevant columns
new_df['unique_element_sort_tuple'] = new_df['unique_element_sort'].apply(tuple)
new_df['score_list_tuple'] = new_df['score_list'].apply(tuple)

# Group by 'Class' and the new tuple column
replacement_counts = new_df.groupby(['Class', 'unique_element_sort_tuple', 'score_list_tuple']).size().reset_index(name='Count')
replacement_counts

,Class,unique_element_sort_tuple,score_list_tuple,Count
0,Generator Expression,"(For Loop with 1 List to iterate, Simple Assig...","(1.0, 1.0, 2.0, 2.0)",1
1,Generator Expression,"(For Loop with Tuple as name, Return, Simple A...","(1.0, 1.0, 1.0, 1.0, 2.0, 2.0)",2
2,Generator Expression,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 2.0, 2.0)",1
3,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 1.0, 2.0)",2
4,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0, 4.0)",2
5,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0, 2.0)",1
6,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",4
7,Generator Expression,"(Simple Assignment, Simple For Loop, Simple If...","(1.0, 1.0, 1.0, 3.0, 4.0)",3
8,Generator Function (yield),"(For Loop with 1 List to iterate, Generator Fu...","(1.0, 1.0, 2.0, 2.0, 5.0)",1
9,Generator Function (yield),"(Generator Function (yield), Simple For Loop)","(1.0, 5.0)",2
10,Generator Function (yield),"(Return, Simple Assignment, Simple Atributte, ...","(1.0, 1.0, 1.0, 1.0, 1.0, 2.0)",1
11,Generator Function (yield),"(Return, Simple Assignment, Simple Atributte, ...","(1.0, 1.0, 1.0, 1.0, 2.0)",2
12,Generator Function (yield),"(Return,)","(1.0,)",7
13,Generator Function (yield),"(pass' statement,)","(3.0,)",1
14,Import'importlib' module,"(Exception --> try/except, For Loop with 1 Tup...","(1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0)",1
15,Import'pickle' module,"(nan,)","(nan,)",1
16,Import're' module,"(Function with Simple argument, Generator Expr...","(1.0, 1.0, 1.0, 1.0, 5.0)",1
17,Import're' module,"(nan,)","(nan,)",3
18,Import'struct' module,"(nan,)","(nan,)",1
19,List Comprehension with 1If statements,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 1.0, 2.0, 2.0)",1
20,List Comprehension with 1If statements,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 1.0, 2.0)",1
21,Simple Dictionary Comprehension,"(Return, Simple Assignment, Simple Atributte, ...","(1.0, 1.0, 1.0, 2.0, 2.0)",2
22,Simple Dictionary Comprehension,"(Return, Simple Assignment, Simple Dictionary,...","(1.0, 1.0, 1.0, 1.0, 2.0)",1
23,Simple Dictionary Comprehension,"(Simple Assignment, Simple Atributte, Simple D...","(1.0, 1.0, 2.0, 2.0)",3
24,Simple List Comprehension,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 2.0, 2.0, 2.0)",1
25,Simple List Comprehension,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",4
26,Super Function,"(Return, Simple Atributte)","(1.0, 2.0)",3
27,Super Function,"(Simple Atributte,)","(2.0,)",6
28,map' call function,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",1

In [10]:
sort_replacement = replacement_counts.sort_values(by='Count', ascending=False)
sort_replacement

,Class,unique_element_sort_tuple,score_list_tuple,Count
12,Generator Function (yield),"(Return,)","(1.0,)",7
27,Super Function,"(Simple Atributte,)","(2.0,)",6
6,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",4
25,Simple List Comprehension,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",4
26,Super Function,"(Return, Simple Atributte)","(1.0, 2.0)",3
7,Generator Expression,"(Simple Assignment, Simple For Loop, Simple If...","(1.0, 1.0, 1.0, 3.0, 4.0)",3
17,Import're' module,"(nan,)","(nan,)",3
23,Simple Dictionary Comprehension,"(Simple Assignment, Simple Atributte, Simple D...","(1.0, 1.0, 2.0, 2.0)",3
9,Generator Function (yield),"(Generator Function (yield), Simple For Loop)","(1.0, 5.0)",2
3,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 1.0, 2.0)",2
4,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0, 4.0)",2
21,Simple Dictionary Comprehension,"(Return, Simple Assignment, Simple Atributte, ...","(1.0, 1.0, 1.0, 2.0, 2.0)",2
11,Generator Function (yield),"(Return, Simple Assignment, Simple Atributte, ...","(1.0, 1.0, 1.0, 1.0, 2.0)",2
1,Generator Expression,"(For Loop with Tuple as name, Return, Simple A...","(1.0, 1.0, 1.0, 1.0, 2.0, 2.0)",2
22,Simple Dictionary Comprehension,"(Return, Simple Assignment, Simple Dictionary,...","(1.0, 1.0, 1.0, 1.0, 2.0)",1
0,Generator Expression,"(For Loop with 1 List to iterate, Simple Assig...","(1.0, 1.0, 2.0, 2.0)",1
24,Simple List Comprehension,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 2.0, 2.0, 2.0)",1
19,List Comprehension with 1If statements,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 1.0, 2.0, 2.0)",1
20,List Comprehension with 1If statements,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 1.0, 2.0)",1
14,Import'importlib' module,"(Exception --> try/except, For Loop with 1 Tup...","(1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0)",1
18,Import'struct' module,"(nan,)","(nan,)",1
16,Import're' module,"(Function with Simple argument, Generator Expr...","(1.0, 1.0, 1.0, 1.0, 5.0)",1
15,Import'pickle' module,"(nan,)","(nan,)",1
13,Generator Function (yield),"(pass' statement,)","(3.0,)",1
10,Generator Function (yield),"(Return, Simple Assignment, Simple Atributte, ...","(1.0, 1.0, 1.0, 1.0, 1.0, 2.0)",1
8,Generator Function (yield),"(For Loop with 1 List to iterate, Generator Fu...","(1.0, 1.0, 2.0, 2.0, 5.0)",1
5,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0, 2.0)",1
2,Generator Expression,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 2.0, 2.0)",1
28,map' call function,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",1

## Generator Expression (16)

In [11]:
genex = sort_replacement[sort_replacement['Class'] == "Generator Expression"]
genex

,Class,unique_element_sort_tuple,score_list_tuple,Count
6,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",4
7,Generator Expression,"(Simple Assignment, Simple For Loop, Simple If...","(1.0, 1.0, 1.0, 3.0, 4.0)",3
3,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 1.0, 2.0)",2
4,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0, 4.0)",2
1,Generator Expression,"(For Loop with Tuple as name, Return, Simple A...","(1.0, 1.0, 1.0, 1.0, 2.0, 2.0)",2
0,Generator Expression,"(For Loop with 1 List to iterate, Simple Assig...","(1.0, 1.0, 2.0, 2.0)",1
5,Generator Expression,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0, 2.0)",1
2,Generator Expression,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 2.0, 2.0)",1

In [12]:
genex.to_csv('result/element/generator-expression.csv')

## Simple List Comprehension (5)

In [13]:
simlist = sort_replacement[sort_replacement['Class'] == "Simple List Comprehension"]
simlist

,Class,unique_element_sort_tuple,score_list_tuple,Count
25,Simple List Comprehension,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",4
24,Simple List Comprehension,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 2.0, 2.0, 2.0)",1

In [14]:
simlist.to_csv('result/element/simple-list-comprehension.csv')

## List Comprehension with 1If statements (2)

In [15]:
listcom = sort_replacement[sort_replacement['Class'] == "List Comprehension with 1If statements"]
listcom

,Class,unique_element_sort_tuple,score_list_tuple,Count
19,List Comprehension with 1If statements,"(For Loop with Tuple as name, Simple Assignmen...","(1.0, 1.0, 1.0, 1.0, 2.0, 2.0)",1
20,List Comprehension with 1If statements,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 1.0, 2.0)",1

In [16]:
listcom.to_csv('result/element/list-comprehension-with-1if-statements.csv')

## Simple Dictionary Comprehension (6)

In [17]:
simdict = sort_replacement[sort_replacement['Class'] == "Simple Dictionary Comprehension"]
simdict

,Class,unique_element_sort_tuple,score_list_tuple,Count
23,Simple Dictionary Comprehension,"(Simple Assignment, Simple Atributte, Simple D...","(1.0, 1.0, 2.0, 2.0)",3
21,Simple Dictionary Comprehension,"(Return, Simple Assignment, Simple Atributte, ...","(1.0, 1.0, 1.0, 2.0, 2.0)",2
22,Simple Dictionary Comprehension,"(Return, Simple Assignment, Simple Dictionary,...","(1.0, 1.0, 1.0, 1.0, 2.0)",1

In [18]:
simdict.to_csv('result/element/simple-dictionary-comprehension.csv')

## map' call function (1)

In [19]:
mapcallfunc = sort_replacement[sort_replacement['Class'] == "map' call function"]
mapcallfunc

,Class,unique_element_sort_tuple,score_list_tuple,Count
28,map' call function,"(Simple Assignment, Simple Atributte, Simple F...","(1.0, 1.0, 1.0, 2.0)",1

In [20]:
mapcallfunc.to_csv('result/element/map-call-function.csv')

## Super Function (9)

In [21]:
supfunc = sort_replacement[sort_replacement['Class'] == "Super Function"]
supfunc

             Class   unique_element_sort_tuple score_list_tuple  Count
27  Super Function         (Simple Atributte,)           (2.0,)      6
26  Super Function  (Return, Simple Atributte)       (1.0, 2.0)      3

In [22]:
supfunc.to_csv('result/element/super-function.csv')